### ISSUE TITLE
extension not working

### ISSUE THREAD

**Issue by wildbill562** [rexxars/view-background-image#1]
this extension is not working. 
![view background image not working](https://cloud.githubusercontent.com/assets/17795609/13721925/1a5c58a4-e803-11e5-9094-233cb2ef7c9d.jpg)

**Comment by rexxars** [comment]
Works for me (on that same page). Somehow the page looks totally different for me, though.

**Comment by wildbill562** [comment]
I tested all 3 apps available and only the last one works for me. btw, I have my browser set to 125% zoom. My screen resolution is 1440 x 900. 
![view background image extension that works](https://cloud.githubusercontent.com/assets/17795609/13722190/d28f6324-e80a-11e5-8f1a-e461e8999a3f.jpg)
